[package]
name = "synth_jxrs"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.3"
rand = "0.8.5"
slint = "1.7.1"
tokio = { version = "1.39.2", features = ["sync", "rt", "macros", "rt-multi-thread"] }
tokio-macros = "2.4.0"
