export enum AmpProps { attack, decay, sustain, release, gain, mode }
export enum OscProps { bypass, coarse, fine, fm_range, freq, gain, mode, output, waveform }

export global Logic {
    pure callback set_precision(float, int) -> string;
}

export component ChangeObserver {
    in property <int> value;
    pure callback changed(int, float) -> float;

    width: 0; height: 0; visible: false;
    opacity: changed(value, 1);
}