import { ComboBox, HorizontalBox, LineEdit, TabWidget, Switch } from "std-widgets.slint";

    export enum OscProps { attack, bypass, decay, freq, gain, master, mode, release, sustain, waveform }

    export global Util {
        pure callback set_precision(float, int) -> string;
    }

    component ChangeObserver {
        in property <int> value;
        pure callback changed(int, float) -> float;

        width: 0; height: 0; visible: false;
        opacity: changed(value, 1);
    }

    component KnobBackground inherits Path {
        in property <length> thickness;
        in property <float> size;

        stroke: black;
        stroke-width: thickness;

        viewbox-width: size;
        viewbox-height: size;

        // path just constructs a circle outline:

        MoveTo {
            x: size / 2;
            y: size;
        }
        ArcTo {
            sweep: true;
            radius-x: size / 2;
            radius-y: size / 2;
            x: size / 2;
            y: 0;
        }
        ArcTo {
            sweep: true;
            radius-x: size / 2;
            radius-y: size / 2;
            x: size / 2;
            y: size;
        }
    }

    component KnobEmpty inherits Path {
        in property <length> thickness;
        in property <float> size;

        stroke: @linear-gradient(0deg, #232629 0%, #393c40 100%);
        stroke-width: thickness;

        viewbox-width: size;
        viewbox-height: size;

        MoveTo {
            x: size / 2;
            y: size;
        }
        ArcTo {
            large-arc: true;
            sweep: true;
            radius-x: size / 2;
            radius-y: size / 2;
            x: size;
            y: size / 2;
        }
    }

    component KnobFill inherits Path {
        in property <length> thickness;
        in property <float> size;
        in property <float> progress;
        in property <color> color;

        stroke: color;
        stroke-width: thickness;

        viewbox-width: size;
        viewbox-height: size;
        MoveTo {
            x: size / 2;
            y: size;
        }
        // draw a section of a (near) circle from the bottom of the knob to the appropriate value:
        ArcTo {
            // this large-arc assignment helps keep the curve mostly aligned to the circle
            large-arc: progress >= 0.67 ? true : false;
            sweep: true;
            radius-x: size / 2;
            radius-y: size / 2;
            x: (size / 2) - (size / 2) * sin(progress * 270deg);
            y: (size / 2) + (size / 2) * cos(progress * 270deg);
        }
    }

    component Knob inherits Rectangle {
        in property <length> thickness: 10px;
        in property <length> size: 250px;
        in property <int> precision: 2;
        in-out property <float> progress;
        in-out property <float> value;
        in property <color> accent-color: blue;
        in property <string> text;

        callback changed;
        callback double-clicked;
        callback text_input_accepted(string);

        width: size / 2 + 10px;
        height: size / 2 + 50px;

        VerticalLayout {
            spacing: 5px;
            padding: 5px; 
            alignment: center;

            Text {
                horizontal-alignment: center;
                text: root.text;
            }
            Rectangle {
                width: root.size / 2;
                height: root.size / 2;
                border-radius: size/2;
                background: @linear-gradient(0deg, #4f5d6e 0%, #939aa3 100%);

                KnobBackground {
                    thickness: root.thickness;
                    size: root.size / 1px;
                }
                KnobEmpty {
                    thickness: root.thickness;
                    size: root.size / 1px;
                }
                KnobFill {
                    thickness: root.thickness;
                    size: root.size / 1px;
                    progress <=> root.progress;
                    color: root.accent-color;
                }
                Rectangle {
                    // TODO: this math technically works ok, but isn't perfect. workshop better solutions
                    background: root.accent-color;
                    width: root.size / 35;
                    height: root.size / 35;
                    border-radius: self.width / 2;

                    x: ((root.size / 4) - sin(root.progress * 270deg) * (root.size / 6)) - (self.width / 2);
                    y: ((root.size / 4) + cos(root.progress * 270deg) * (root.size / 6)) - (self.height / 2);
                }
                area := TouchArea {
                    height: root.size / 2 - 40px;

                    moved => {
                        root.progress = self.mouse-y > self.pressed-y ?
                            max(0.0, (root.progress) - ((self.mouse-y) - self.pressed-y) / 5000px)
                            : min(1.0, root.progress + ((self.pressed-y) - self.mouse-y) / 5000px);
                        root.changed();
                    }
                    double-clicked => {
                        root.double-clicked();
                    }
                }
            } // Rectangle
            input_field := LineEdit {
                width: root.size / 3;
                input-type: decimal;
                placeholder-text: Util.set_precision(root.value, root.precision);

                accepted(s) => {
                    root.text_input_accepted(s);
                    self.text = ""; // clears the editing text, allowing the placeholder text to update again
                    fs.focus(); // takes focus from the text field
                    root.changed();
                }
            }
        }

        fs := FocusScope { } // hacky solution to remove focus from other elements
    }

    component Oscillator inherits Rectangle {
        in-out property <float> frequency: 440;
        in-out property <float> gain: 0;
        in-out property <float> attack: 0;
        in-out property <float> decay: 0;
        in-out property <float> sustain: 1;
        in-out property <float> release: 0;
        in property <color> accent-color: blue;

        pure callback changed(OscProps, float);

        border-radius: 10px;
        background: @linear-gradient(0deg, #4f5d6e 0%, #939aa3 100%);

        GridLayout {
            padding: 10px;
            spacing: 10px;

            Row {
                Switch {
                    toggled => {
                        // switch on = oscillator on, bypass off; switch off = oscillator off, bypass on
                        self.checked ? root.changed(OscProps.bypass, 0) : root.changed(OscProps.bypass, 1);
                    }
                }
                ComboBox {
                    model: ["Noise", "Saw", "Sine", "Square", "Triangle"];
                    current-value: "Sine";

                    selected(s) => {
                        root.changed(OscProps.waveform, self.current-index);
                    }
                }
            } // Row [0]

            Row {
                tabs := TabWidget {
                    Tab { // 0
                        title: "Freq";
                        freq_knob := Knob {
                            text: "FREQUENCY (HZ)";
                            value <=> root.frequency;
                            progress: ((self.value) - 10.0) * 0.0005;
                            size: 200px;
                            accent-color: root.accent-color;

                            changed => {
                                self.value = self.progress / 0.0005 + 10.0;
                                root.changed(OscProps.freq, self.value);
                            }
                            double-clicked => {
                                self.value = 440;
                                self.progress = ((self.value) - 10.0) * 0.0005;
                            }
                            text_input_accepted(s) => {
                                self.value = max(10, (min(2010, s.to-float())));
                                self.progress = ((self.value) - 10.0) * 0.0005;
                            }
                        }
                    }
                    Tab { // 1
                        title: "MIDI";
                    }
                } // tabs

                amp := Rectangle {
                    border-color: #3b4757;
                    border-width: 2px;
                    min-height: 480px;

                    VerticalLayout {
                        padding: 5px;
                        spacing: 20px;
                        alignment: center;

                        gain_knob := Knob {
                            text: "GAIN (dB)";
                            value <=> root.gain;
                            progress: (self.value + 60) / 60;

                            size: 200px;
                            accent-color: root.accent-color;

                            changed => {
                                self.value = self.progress * 60 - 60;
                                root.changed(OscProps.gain, self.value);
                            }
                            double-clicked => {
                                self.value = 0;
                                self.progress = (self.value + 60) / 60;
                            }
                            text_input_accepted(s) => {
                                self.value = max(-60, min(0, s.to-float()));
                                self.progress = (self.value + 60) / 60;
                            }
                        }
                        GridLayout {
                            spacing: 10px;

                            Row {
                                attack_knob := Knob {
                                    text: "ATTACK (ms)";
                                    value <=> root.attack;
                                    progress: self.value / 1000;

                                    size: 150px;
                                    accent-color: root.accent-color;

                                    changed => {
                                        self.value = self.progress * 1000;
                                        root.changed(OscProps.attack, attack_knob.value / 100);
                                    }
                                    double-clicked => {
                                        self.value = 0;
                                        self.progress = self.value / 1000;
                                    }
                                    text_input_accepted(s) => {
                                        self.value = max(0, min(1000, s.to-float()));
                                        self.progress = self.value / 1000;
                                    }
                                } // attack_knob
                                decay_knob := Knob {
                                    text: "DECAY (ms)";
                                    value <=> root.decay;
                                    progress: self.value / 1000;

                                    size: 150px;
                                    accent-color: root.accent-color;

                                    changed => {
                                        self.value = self.progress * 1000;
                                        root.changed(OscProps.decay, self.value / 100);
                                    }
                                    double-clicked => {
                                        self.value = 0;
                                        self.progress = self.value / 1000;
                                    }
                                    text_input_accepted(s) => {
                                        self.value = max(0, min(1000, s.to-float()));
                                        self.progress = self.value / 1000;
                                    }
                                } // decay_knob
                            }
                            Row {
                                sustain_knob := Knob {
                                    text: "SUSTAIN";
                                    value <=> root.sustain;
                                    progress: self.value;

                                    size: 150px;
                                    accent-color: root.accent-color;

                                    changed => {
                                        self.value = self.progress;
                                        root.changed(OscProps.sustain, self.value);
                                    }
                                    double_clicked => {
                                        self.value = 1;
                                        self.progress = self.value;
                                    }
                                    text_input_accepted(s) => {
                                        self.value = max(0, min(1, s.to-float()));
                                        self.progress = self.value;
                                    }
                                } // sustain_knob
                                release_knob := Knob {
                                    text: "RELEASE (ms)";
                                    value <=> root.release;
                                    progress: self.value / 1000;

                                    size: 150px;
                                    accent-color: root.accent-color;

                                    changed => {
                                        self.value = self.progress * 1000;
                                        root.changed(OscProps.release, self.value / 100);
                                    }
                                    double_clicked => {
                                        self.value = 0;
                                        self.progress = self.value / 1000;
                                    }
                                    text_input_accepted(s) => {
                                        self.value = max(0, min(1000, s.to-float()));
                                        self.progress = self.value / 1000;
                                    }
                                } // release_knob
                            }
                        }
                    }
                } // amp

            }
        } // GridLayout

        // Slint's built-in TabWidget has no callback for listening for the active tab to
        // change. This solution is thanks to user maurges's solution in discussion post #4717
        // on Slint's GitHub repository.
        ChangeObserver {
            value: tabs.current-index;

            changed(v, f) => {
                root.changed(OscProps.mode, v);

                return f;
            }
        }
    }

    export component MainWindow inherits Window {
        property <float> master: 1.0;

        pure callback prop_changed(int, OscProps, float);

        background: @linear-gradient(0deg, #000000 0%, #232629 100%);

        GridLayout {
            padding: 20px;
            spacing: 10px;
            spacing-vertical: 20px;

            Row {
                HorizontalLayout {
                    alignment: space-between;

                    master_gain := Knob {
                        text: "MASTER (dB)";
                        value <=> root.master;
                        progress: (self.value + 60) / 60;
    
                        size: 150px;
                        accent-color: white;
    
                        changed => {
                            self.value = self.progress * 60 - 60;
                            root.prop_changed(0, OscProps.master, self.value);
                        }
                        double-clicked => {
                            self.value = 0;
                            self.progress = (self.value + 60) / 60;
                        }
                        text_input_accepted(s) => {
                            self.value = max(-60, min(0, s.to-float()));
                            self.progress = (self.value + 60) / 60;
                        }
                    }
                }
            }
            Row {
                osc1 := Oscillator {
                    accent-color: @linear-gradient(0deg, #0768b8 0%, #16b4e4 100%);
    
                    changed(prop, val) => {
                        root.prop_changed(0, prop, val);
                    }
                }
                osc2 := Oscillator {
                    accent-color: @linear-gradient(0deg, #aa0a6d 0%, #db2cc4 100%);
    
                    changed(prop, val) => {
                        root.prop_changed(1, prop, val);
                    }
                }
                osc3 := Oscillator {
                    accent-color: @linear-gradient(0deg, #da460c 0%, #e76a17 100%);
    
                    changed(prop, val) => {
                        root.prop_changed(2, prop, val);
                    }
                }
            }
        }
    }